import { Agent17Researcher } from '../../types';

export const MOCK_FACULTY_RESEARCHERS: Agent17Researcher[] = [
  {
    researcher_id: 'FAC-A17-001',
    name: 'Dr. Aris Thorne',
    department: 'Department of Computer Science & Engineering',
    institution: 'Vignan Foundation for Science, Technology & Research',
    affiliation: 'School of Computing, Vignan University',
    scopus_author_id: '57193240112',
    orcid: '0000-0002-4910-3819',
    wos_researcher_id: 'AAY-9481-2021',
    expertise: ['Multi-Agent Systems', 'Reinforcement Learning', 'Autonomous Decision Making', 'Decentralized Coordination'],
    research_areas: ['Artificial Intelligence', 'Multi-Agent Systems', 'Distributed Systems'],
    keywords: ['autonomous agents', 'multi-agent reinforcement learning', 'marl', 'cooperative game theory', 'consensus protocols'],
    h_index: 28,
    i10_index: 46,
    total_citations: 3420,
    current_workload: 2,
    max_workload: 5,
    is_available: true,
    co_authors: ['Dr. Radhika Sharma', 'Prof. Elena Rostova', 'Dr. Kenji Sato'],
    publications: [
      {
        title: 'Scalable Consensus in Decentralized Multi-Agent Swarms under Adversarial Conditions',
        year: 2025,
        doi: '10.1109/AIAI.2025.0192',
        citations: 24,
        venue: 'IEEE Transactions on Autonomous Systems',
        co_authors: ['Dr. Kenji Sato'],
        domain: 'Multi-Agent Systems',
        keywords: ['swarm intelligence', 'consensus protocols', 'adversarial robustness']
      },
      {
        title: 'Hierarchical Multi-Agent Reinforcement Learning for Dynamic Traffic Optimization',
        year: 2024,
        doi: '10.1145/3612841',
        citations: 45,
        venue: 'ACM Transactions on Intelligent Systems and Technology',
        co_authors: ['Dr. Radhika Sharma'],
        domain: 'Artificial Intelligence',
        keywords: ['reinforcement learning', 'hierarchical control', 'traffic management']
      },
      {
        title: 'Decentralized Resource Allocation Using Competitive Multi-Agent Auctions',
        year: 2023,
        doi: '10.1016/j.artint.2023.103829',
        citations: 62,
        venue: 'Artificial Intelligence Journal',
        co_authors: ['Prof. Elena Rostova'],
        domain: 'Multi-Agent Systems',
        keywords: ['auctions', 'game theory', 'resource allocation']
      },
      {
        title: 'Graph Neural Policies for Emergent Communication in Multi-Agent Environments',
        year: 2023,
        doi: '10.1007/s10994-023-06312-x',
        citations: 51,
        venue: 'Machine Learning',
        co_authors: ['Dr. Kenji Sato'],
        domain: 'Deep Learning',
        keywords: ['graph neural networks', 'communication protocols', 'marl']
      },
      {
        title: 'Safe Exploration in Continuous Action Space Multi-Agent MDPs',
        year: 2022,
        doi: '10.1609/aaai.v36i7.20641',
        citations: 88,
        venue: 'AAAI Conference on Human Computation and Artificial Intelligence',
        co_authors: ['Dr. Kenji Sato'],
        domain: 'Reinforcement Learning',
        keywords: ['safe rl', 'constrained mdp', 'continuous control']
      },
      {
        title: 'Self-Organizing Agent Architectures for Resilient Microgrid Power Dispatch',
        year: 2021,
        doi: '10.1109/TSG.2021.3082910',
        citations: 95,
        venue: 'IEEE Transactions on Smart Grid',
        co_authors: ['Dr. Radhika Sharma'],
        domain: 'Distributed Systems',
        keywords: ['microgrid', 'smart grid', 'agent coordination']
      },
      {
        title: 'Fault-Tolerant Leader Election in Byzantine Agent Networks',
        year: 2020,
        doi: '10.1016/j.ins.2020.04.019',
        citations: 73,
        venue: 'Information Sciences',
        co_authors: [],
        domain: 'Multi-Agent Systems',
        keywords: ['byzantine fault tolerance', 'leader election', 'distributed consensus']
      },
      {
        title: 'Decentralized Multi-Agent Auction Protocols for Renewable Energy Markets',
        year: 2020,
        doi: '10.1109/TSTE.2020.2981920',
        citations: 85,
        venue: 'IEEE Transactions on Sustainable Energy',
        co_authors: ['Dr. Radhika Sharma'],
        domain: 'Multi-Agent Systems',
        keywords: ['auction protocols', 'energy trading', 'smart grid']
      },
      {
        title: 'Adversarial Defense in Decentralized Multi-Agent Consensus Swarms',
        year: 2019,
        doi: '10.1016/j.adhoc.2019.101928',
        citations: 68,
        venue: 'Ad Hoc Networks',
        co_authors: [],
        domain: 'Distributed Systems',
        keywords: ['swarms', 'byzantine defense', 'consensus']
      }
    ]
  },
  {
    researcher_id: 'FAC-A17-002',
    name: 'Prof. Sofia Chen',
    department: 'Institute for Artificial Intelligence',
    institution: 'National University of Singapore',
    affiliation: 'NUS School of Computing',
    scopus_author_id: '56829103948',
    orcid: '0000-0003-1928-3011',
    wos_researcher_id: 'BBR-4019-2020',
    expertise: ['Large Language Models', 'Chain-of-Thought Reasoning', 'Prompt Engineering', 'Cognitive Architectures'],
    research_areas: ['Natural Language Processing', 'Deep Learning', 'Artificial Intelligence'],
    keywords: ['llm', 'chain of thought', 'reasoning', 'rag', 'transformer architectures', 'few-shot learning'],
    h_index: 34,
    i10_index: 68,
    total_citations: 5820,
    current_workload: 1,
    max_workload: 4,
    is_available: true,
    co_authors: ['Dr. Marcus Holloway', 'Dr. Priya Venkatesh'],
    publications: [
      {
        title: 'Self-Reflective Reasoning in Large Language Models with Verification Trees',
        year: 2025,
        doi: '10.18653/v1/2025.acl-long.421',
        citations: 39,
        venue: 'Proceedings of the Annual Meeting of the Association for Computational Linguistics (ACL)',
        co_authors: ['Dr. Marcus Holloway'],
        domain: 'Natural Language Processing',
        keywords: ['self reflection', 'verification trees', 'chain of thought']
      },
      {
        title: 'Dynamic Retrieval-Augmented Generation with Parametric Memory Alignment',
        year: 2024,
        doi: '10.18653/v1/2024.emnlp-main.112',
        citations: 110,
        venue: 'Empirical Methods in Natural Language Processing (EMNLP)',
        co_authors: ['Dr. Priya Venkatesh'],
        domain: 'Natural Language Processing',
        keywords: ['rag', 'dense retrieval', 'parametric memory']
      },
      {
        title: 'Hallucination Mitigation in Instruction-Tuned Models via Counterfactual Consistency',
        year: 2024,
        doi: '10.1145/3641201',
        citations: 82,
        venue: 'ACM Computing Surveys',
        co_authors: [],
        domain: 'Deep Learning',
        keywords: ['hallucination mitigation', 'counterfactual inference', 'alignment']
      },
      {
        title: 'Zero-Shot Multi-Hop Question Answering through Symbolic Fact Graph Synthesis',
        year: 2023,
        doi: '10.1609/aaai.v37i11.26410',
        citations: 145,
        venue: 'AAAI Conference on Artificial Intelligence',
        co_authors: ['Dr. Marcus Holloway'],
        domain: 'Artificial Intelligence',
        keywords: ['multi-hop qa', 'symbolic graphs', 'knowledge graphs']
      },
      {
        title: 'Token-Level Uncertainty Calibration in Generative Pre-Trained Transformers',
        year: 2023,
        doi: '10.1109/TASLP.2023.3274910',
        citations: 94,
        venue: 'IEEE/ACM Transactions on Audio, Speech, and Language Processing',
        co_authors: ['Dr. Priya Venkatesh'],
        domain: 'Natural Language Processing',
        keywords: ['uncertainty calibration', 'confidence scoring', 'token logits']
      },
      {
        title: 'Cross-Lingual Transferability of Dense Passage Encoders',
        year: 2022,
        doi: '10.18653/v1/2022.naacl-main.87',
        citations: 120,
        venue: 'NAACL-HLT',
        co_authors: [],
        domain: 'Information Retrieval',
        keywords: ['dense retrieval', 'cross-lingual', 'multilingual nlp']
      },
      {
        title: 'Attention Distillation for Low-Resource Domain Adaptation',
        year: 2021,
        doi: '10.1007/s10994-021-05991-0',
        citations: 78,
        venue: 'Machine Learning Journal',
        co_authors: ['Dr. Marcus Holloway'],
        domain: 'Deep Learning',
        keywords: ['knowledge distillation', 'domain adaptation', 'low resource']
      }
    ]
  },
  {
    researcher_id: 'FAC-A17-003',
    name: 'Dr. Vikramaditya Rao',
    department: 'Department of Cybersecurity & Cryptology',
    institution: 'Indian Institute of Technology Madras',
    affiliation: 'Centre for Cyber Security Studies, IIT Madras',
    scopus_author_id: '57199481023',
    orcid: '0000-0001-7291-8841',
    wos_researcher_id: 'CCX-1942-2019',
    expertise: ['Adversarial Machine Learning', 'AI Agent Sandboxing', 'Zero-Trust Architectures', 'Model Inversion Defense'],
    research_areas: ['Cybersecurity', 'Trustworthy AI', 'Machine Learning'],
    keywords: ['cybersecurity', 'adversarial attacks', 'sandboxing', 'zero-trust', 'data poisoning', 'differential privacy'],
    h_index: 31,
    i10_index: 52,
    total_citations: 4190,
    current_workload: 3,
    max_workload: 5,
    is_available: true,
    co_authors: ['Dr. Ananya Joshi', 'Dr. Liam O’Connor'],
    publications: [
      {
        title: 'Jailbreak Resistant Guardrails for Autonomous Agent API Executions',
        year: 2025,
        doi: '10.1109/SP.2025.1042',
        citations: 31,
        venue: 'IEEE Symposium on Security and Privacy (S&P)',
        co_authors: ['Dr. Ananya Joshi'],
        domain: 'Cybersecurity',
        keywords: ['prompt injection', 'jailbreak defense', 'agent guardrails']
      },
      {
        title: 'Provable Sandboxing of Code Generation Agents in Enterprise Workflows',
        year: 2024,
        doi: '10.1145/3658644.3670391',
        citations: 68,
        venue: 'ACM Conference on Computer and Communications Security (CCS)',
        co_authors: ['Dr. Liam O’Connor'],
        domain: 'Cybersecurity',
        keywords: ['sandboxing', 'code generation', 'least privilege']
      },
      {
        title: 'Certifiably Robust Prompt Defenses against Backdoor Injection Attacks',
        year: 2024,
        doi: '10.1109/TDSC.2024.3391024',
        citations: 55,
        venue: 'IEEE Transactions on Dependable and Secure Computing',
        co_authors: [],
        domain: 'Trustworthy AI',
        keywords: ['backdoor attacks', 'certified robustness', 'prompt sanitization']
      },
      {
        title: 'Differential Privacy Guarantees in Distributed Agentic Learning Networks',
        year: 2023,
        doi: '10.1145/3576915.3623120',
        citations: 89,
        venue: 'ACM Transactions on Privacy and Security',
        co_authors: ['Dr. Ananya Joshi'],
        domain: 'Cybersecurity',
        keywords: ['differential privacy', 'federated agents', 'privacy leakage']
      },
      {
        title: 'Adversarial Perturbation Detection in Vision-Language Autonomous Navigation',
        year: 2022,
        doi: '10.1109/TIFS.2022.3194012',
        citations: 104,
        venue: 'IEEE Transactions on Information Forensics and Security',
        co_authors: ['Dr. Liam O’Connor'],
        domain: 'Computer Vision',
        keywords: ['adversarial perturbation', 'vision-language models', 'navigation safety']
      },
      {
        title: 'Zero-Knowledge Proofs for Verifiable AI Model Inferences on the Edge',
        year: 2021,
        doi: '10.1016/j.cose.2021.102390',
        citations: 77,
        venue: 'Computers & Security',
        co_authors: [],
        domain: 'Blockchain',
        keywords: ['zero knowledge proofs', 'verifiable inference', 'edge security']
      }
    ]
  },
  {
    researcher_id: 'FAC-A17-004',
    name: 'Dr. Kenji Sato',
    department: 'Department of Mechano-Informatics',
    institution: 'University of Tokyo',
    affiliation: 'Robotics & Embodied AI Laboratory',
    scopus_author_id: '56481920194',
    orcid: '0000-0002-8819-2041',
    wos_researcher_id: 'JPS-2810-2021',
    expertise: ['Embodied AI', 'Robot Manipulation', 'Visual SLAM', 'Sim-to-Real Transfer'],
    research_areas: ['Robotics', 'Computer Vision', 'Edge AI'],
    keywords: ['robotics', 'embodied ai', 'manipulation', 'slam', 'reinforcement learning', 'sim to real', 'quadrupeds'],
    h_index: 25,
    i10_index: 39,
    total_citations: 2840,
    current_workload: 2,
    max_workload: 4,
    is_available: true,
    co_authors: ['Dr. Aris Thorne', 'Dr. Mateo Rossi'],
    publications: [
      {
        title: 'Generalizable Bimanual Robotic Manipulation using Diffusion Policy Transformers',
        year: 2025,
        doi: '10.1109/ICRA.2025.1092',
        citations: 18,
        venue: 'IEEE International Conference on Robotics and Automation (ICRA)',
        co_authors: ['Dr. Mateo Rossi'],
        domain: 'Robotics',
        keywords: ['diffusion policy', 'bimanual manipulation', 'embodied agents']
      },
      {
        title: 'Zero-Shot Sim-to-Real Adaptation of Legged Locomotion on Unstructured Terrains',
        year: 2024,
        doi: '10.1177/02783649241258901',
        citations: 62,
        venue: 'The International Journal of Robotics Research (IJRR)',
        co_authors: ['Dr. Aris Thorne'],
        domain: 'Robotics',
        keywords: ['legged robots', 'sim to real', 'unstructured terrain']
      },
      {
        title: 'Real-Time Edge Visual SLAM with Semantic Feature Pruning for Autonomous Drones',
        year: 2023,
        doi: '10.1109/TRO.2023.3289011',
        citations: 79,
        venue: 'IEEE Transactions on Robotics',
        co_authors: ['Dr. Mateo Rossi'],
        domain: 'Computer Vision',
        keywords: ['visual slam', 'edge computing', 'drone autonomy']
      },
      {
        title: 'Human-in-the-Loop Teleoperation and Policy Blending for Surgical Cobots',
        year: 2022,
        doi: '10.1109/TBME.2022.3182901',
        citations: 58,
        venue: 'IEEE Transactions on Biomedical Engineering',
        co_authors: [],
        domain: 'Human Computer Interaction',
        keywords: ['cobots', 'surgical robotics', 'teleoperation']
      },
      {
        title: 'Tactile Sensing Integration for Compliant Grasping of Fragile Objects',
        year: 2021,
        doi: '10.1109/LRA.2021.3068920',
        citations: 64,
        venue: 'IEEE Robotics and Automation Letters (RA-L)',
        co_authors: ['Dr. Mateo Rossi'],
        domain: 'Robotics',
        keywords: ['tactile sensors', 'fragile grasping', 'gripper compliance']
      }
    ]
  },
  {
    researcher_id: 'FAC-A17-005',
    name: 'Dr. Ananya Joshi',
    department: 'Department of Computer Science',
    institution: 'Vignan Foundation for Science, Technology & Research',
    affiliation: 'Center for Artificial Intelligence Research, Vignan University',
    scopus_author_id: '57210948291',
    orcid: '0000-0003-8821-4902',
    wos_researcher_id: 'IND-9018-2022',
    expertise: ['Computer Vision', 'Deep Learning', 'Medical Image Segmentation', 'Diffusion Models'],
    research_areas: ['Computer Vision', 'Deep Learning', 'Healthcare AI'],
    keywords: ['computer vision', 'medical imaging', 'segmentation', 'object detection', 'diffusion models', 'gan'],
    h_index: 22,
    i10_index: 35,
    total_citations: 2190,
    current_workload: 1,
    max_workload: 5,
    is_available: true,
    co_authors: ['Dr. Radhika Sharma', 'Dr. Vikramaditya Rao'],
    publications: [
      {
        title: 'Weakly-Supervised Polyp Segmentation in Colonoscopy Videos using Spatio-Temporal Attention',
        year: 2025,
        doi: '10.1016/j.media.2024.103310',
        citations: 19,
        venue: 'Medical Image Analysis',
        co_authors: ['Dr. Radhika Sharma'],
        domain: 'Computer Vision',
        keywords: ['medical imaging', 'polyp segmentation', 'video attention']
      },
      {
        title: 'Explainable AI for Diabetic Retinopathy Grading via Counterfactual Saliency Maps',
        year: 2024,
        doi: '10.1109/TMI.2024.3389012',
        citations: 44,
        venue: 'IEEE Transactions on Medical Imaging',
        co_authors: ['Dr. Vikramaditya Rao'],
        domain: 'Healthcare AI',
        keywords: ['diabetic retinopathy', 'counterfactual explanations', 'saliency']
      },
      {
        title: 'Contrastive Representation Learning for 3D Brain MRI Tumor Boundary Delineation',
        year: 2023,
        doi: '10.1007/978-3-031-43907-0_24',
        citations: 58,
        venue: 'MICCAI 2023',
        co_authors: [],
        domain: 'Computer Vision',
        keywords: ['mri segmentation', 'brain tumor', 'contrastive learning']
      },
      {
        title: 'Low-Light Video Enhancement with Retinex-Guided Generative Adversarial Networks',
        year: 2022,
        doi: '10.1109/TIP.2022.3178210',
        citations: 72,
        venue: 'IEEE Transactions on Image Processing',
        co_authors: ['Dr. Radhika Sharma'],
        domain: 'Computer Vision',
        keywords: ['low-light enhancement', 'retinex theory', 'gan']
      },
      {
        title: 'Edge-Preserving Ultrasound Speckle Reduction using Wavelet-Based Autoencoders',
        year: 2021,
        doi: '10.1016/j.bspc.2021.102810',
        citations: 65,
        venue: 'Biomedical Signal Processing and Control',
        co_authors: [],
        domain: 'Computer Vision',
        keywords: ['ultrasound denoising', 'wavelet transform', 'autoencoders']
      }
    ]
  },
  {
    researcher_id: 'FAC-A17-006',
    name: 'Prof. Lucas Meyer',
    department: 'Department of Electrical & Computer Engineering',
    institution: 'Technical University of Munich',
    affiliation: 'TUM School of Computation, Information and Technology',
    scopus_author_id: '56102938471',
    orcid: '0000-0001-9283-7461',
    wos_researcher_id: 'DEU-3829-2018',
    expertise: ['Edge Computing', 'IoT Architectures', 'Low-Power Neural Inference', 'TinyML'],
    research_areas: ['Edge AI', 'IoT', 'Cloud Computing', 'Distributed Systems'],
    keywords: ['tinyml', 'edge ai', 'iot', 'energy efficiency', 'quantization', 'mcu inference', 'fog computing'],
    h_index: 37,
    i10_index: 74,
    total_citations: 6410,
    current_workload: 2,
    max_workload: 4,
    is_available: true,
    co_authors: ['Dr. Priya Venkatesh', 'Dr. Mateo Rossi'],
    publications: [
      {
        title: 'Sub-Milliwatt Vision Transformers on Microcontrollers using 4-Bit Integer Arithmetic',
        year: 2025,
        doi: '10.1145/3691230',
        citations: 28,
        venue: 'ACM Transactions on Embedded Computing Systems',
        co_authors: ['Dr. Priya Venkatesh'],
        domain: 'Edge AI',
        keywords: ['tinyml', 'integer quantization', 'microcontrollers']
      },
      {
        title: 'Decentralized Federated Learning for Predictive Maintenance in Industrial IoT',
        year: 2024,
        doi: '10.1109/TII.2024.3361820',
        citations: 82,
        venue: 'IEEE Transactions on Industrial Informatics',
        co_authors: ['Dr. Mateo Rossi'],
        domain: 'IoT',
        keywords: ['industrial iot', 'predictive maintenance', 'federated learning']
      },
      {
        title: 'Dynamic Task Offloading in 5G-Enabled Cloud-Edge Collaborations',
        year: 2023,
        doi: '10.1109/TMC.2023.3281092',
        citations: 115,
        venue: 'IEEE Transactions on Mobile Computing',
        co_authors: [],
        domain: 'Cloud Computing',
        keywords: ['task offloading', '5g', 'edge computing']
      },
      {
        title: 'Energy-Harvesting IoT Sensor Nodes with Intermittent Deep Neural Processing',
        year: 2022,
        doi: '10.1145/3534086.3534321',
        citations: 91,
        venue: 'ACM/IEEE International Conference on Information Processing in Sensor Networks (IPSN)',
        co_authors: ['Dr. Priya Venkatesh'],
        domain: 'IoT',
        keywords: ['energy harvesting', 'intermittent computing', 'embedded sensors']
      },
      {
        title: 'Zero-Latency Anomaly Detection in Smart Grid Phasor Measurement Units',
        year: 2021,
        doi: '10.1109/TSG.2021.3102918',
        citations: 87,
        venue: 'IEEE Transactions on Smart Grid',
        co_authors: [],
        domain: 'Distributed Systems',
        keywords: ['smart grid', 'anomaly detection', 'phasor measurement']
      }
    ]
  },
  {
    researcher_id: 'FAC-A17-007',
    name: 'Dr. Priya Venkatesh',
    department: 'Department of Computer Science',
    institution: 'Carnegie Mellon University',
    affiliation: 'Language Technologies Institute, CMU',
    scopus_author_id: '57291840192',
    orcid: '0000-0002-7104-9810',
    wos_researcher_id: 'USA-8291-2022',
    expertise: ['Information Retrieval', 'Vector Search', 'Semantic Indexing', 'Knowledge Graphs'],
    research_areas: ['Information Retrieval', 'Data Science', 'Natural Language Processing'],
    keywords: ['information retrieval', 'vector search', 'dense passage retrieval', 'hnsw', 'knowledge graphs', 'recommender systems'],
    h_index: 26,
    i10_index: 41,
    total_citations: 2980,
    current_workload: 1,
    max_workload: 5,
    is_available: true,
    co_authors: ['Prof. Sofia Chen', 'Prof. Lucas Meyer'],
    publications: [
      {
        title: 'Hybrid Approximate Nearest Neighbor Search with Learned Graph Partitioning',
        year: 2025,
        doi: '10.1145/3701290',
        citations: 21,
        venue: 'ACM SIGIR Conference on Research and Development in Information Retrieval',
        co_authors: ['Prof. Sofia Chen'],
        domain: 'Information Retrieval',
        keywords: ['ann search', 'vector database', 'hnsw']
      },
      {
        title: 'Personalized Query Expansion using Temporal Entity Knowledge Graphs',
        year: 2024,
        doi: '10.1145/3626772.3657710',
        citations: 49,
        venue: 'Proceedings of the ACM Web Conference (WWW)',
        co_authors: [],
        domain: 'Information Retrieval',
        keywords: ['knowledge graph', 'query expansion', 'entity ranking']
      },
      {
        title: 'Cold-Start Item Recommendation via Multimodal Contrastive Alignment',
        year: 2023,
        doi: '10.1109/TKDE.2023.3291028',
        citations: 74,
        venue: 'IEEE Transactions on Knowledge and Data Engineering',
        co_authors: ['Prof. Lucas Meyer'],
        domain: 'Data Science',
        keywords: ['recommender systems', 'cold start', 'multimodal contrastive']
      },
      {
        title: 'Dense Passage Reranking with Late Interaction Models on Specialized Corpora',
        year: 2022,
        doi: '10.18653/v1/2022.findings-emnlp.310',
        citations: 86,
        venue: 'Findings of EMNLP 2022',
        co_authors: ['Prof. Sofia Chen'],
        domain: 'Natural Language Processing',
        keywords: ['colbert', 'passage reranking', 'dense retrieval']
      },
      {
        title: 'Bias Assessment and Mitigation in Neural Search Engines',
        year: 2021,
        doi: '10.1145/3404835.3462890',
        citations: 92,
        venue: 'ACM SIGIR',
        co_authors: [],
        domain: 'Information Retrieval',
        keywords: ['search bias', 'fairness', 'ranking evaluation']
      }
    ]
  },
  {
    researcher_id: 'FAC-A17-008',
    name: 'Dr. Marcus Holloway',
    department: 'Department of Computer Science',
    institution: 'University of Oxford',
    affiliation: 'Oxford Robotics and Reasoning Group',
    scopus_author_id: '57102938471',
    orcid: '0000-0001-8392-1920',
    wos_researcher_id: 'GBR-7192-2019',
    expertise: ['Symbolic AI', 'Automated Reasoning', 'Neuro-Symbolic AI', 'Knowledge Representation'],
    research_areas: ['Artificial Intelligence', 'Machine Learning', 'Software Engineering'],
    keywords: ['neuro-symbolic', 'knowledge representation', 'sat solvers', 'formal verification', 'logic programming'],
    h_index: 32,
    i10_index: 59,
    total_citations: 4620,
    current_workload: 3,
    max_workload: 5,
    is_available: true,
    co_authors: ['Prof. Sofia Chen', 'Dr. Liam O’Connor'],
    publications: [
      {
        title: 'Integrating Datalog Engines with Neural Language Models for Verifiable Reasoning',
        year: 2025,
        doi: '10.1609/aaai.v39i1.30129',
        citations: 26,
        venue: 'AAAI Conference on Artificial Intelligence',
        co_authors: ['Prof. Sofia Chen'],
        domain: 'Artificial Intelligence',
        keywords: ['datalog', 'neuro-symbolic', 'verifiable reasoning']
      },
      {
        title: 'Satisfiability Modulo Theories for Neural Network Safety Property Verification',
        year: 2024,
        doi: '10.1007/978-3-031-57256-2_14',
        citations: 54,
        venue: 'International Conference on Computer-Aided Verification (CAV)',
        co_authors: ['Dr. Liam O’Connor'],
        domain: 'Software Engineering',
        keywords: ['smt solver', 'formal verification', 'neural network safety']
      },
      {
        title: 'Knowledge-Enhanced Transformer Models for Scientific Hypothesis Formulation',
        year: 2023,
        doi: '10.1038/s42256-023-00681-4',
        citations: 98,
        venue: 'Nature Machine Intelligence',
        co_authors: ['Prof. Sofia Chen'],
        domain: 'Artificial Intelligence',
        keywords: ['hypothesis generation', 'knowledge graph', 'scientific discovery']
      },
      {
        title: 'Inductive Logic Programming with Differentiable Clauses and Soft Unification',
        year: 2022,
        doi: '10.1016/j.artint.2022.103710',
        citations: 88,
        venue: 'Artificial Intelligence Journal',
        co_authors: [],
        domain: 'Machine Learning',
        keywords: ['inductive logic', 'differentiable reasoning', 'soft unification']
      },
      {
        title: 'Constraint-Guided Synthesis of Multi-Agent Communication Protocols',
        year: 2021,
        doi: '10.1145/3460319.3464821',
        citations: 64,
        venue: 'ACM SIGSOFT International Symposium on Software Testing and Analysis',
        co_authors: ['Dr. Liam O’Connor'],
        domain: 'Software Engineering',
        keywords: ['protocol synthesis', 'program verification', 'multi-agent']
      }
    ]
  },
  {
    researcher_id: 'FAC-A17-009',
    name: 'Dr. Liam O’Connor',
    department: 'School of Computing',
    institution: 'Australian National University',
    affiliation: 'Trustworthy Systems Research Group',
    scopus_author_id: '57182940129',
    orcid: '0000-0002-3918-4012',
    wos_researcher_id: 'AUS-9102-2021',
    expertise: ['Formal Methods', 'Smart Contract Auditing', 'Blockchain Security', 'Proof Assistants'],
    research_areas: ['Blockchain', 'Cybersecurity', 'Software Engineering'],
    keywords: ['blockchain', 'smart contracts', 'ethereum', 'formal verification', 'isabelle', 'coq', 'zero-knowledge'],
    h_index: 24,
    i10_index: 38,
    total_citations: 2450,
    current_workload: 2,
    max_workload: 4,
    is_available: true,
    co_authors: ['Dr. Vikramaditya Rao', 'Dr. Marcus Holloway'],
    publications: [
      {
        title: 'Automated Formal Verification of Layer-2 Rollup State Transitions',
        year: 2025,
        doi: '10.1109/SP.2025.1098',
        citations: 15,
        venue: 'IEEE Symposium on Security and Privacy',
        co_authors: ['Dr. Vikramaditya Rao'],
        domain: 'Blockchain',
        keywords: ['layer-2 rollups', 'zk-snark', 'formal verification']
      },
      {
        title: 'DeFi Flash Loan Exploit Detection using Symbolic Model Checking',
        year: 2024,
        doi: '10.1145/3658644.3670410',
        citations: 60,
        venue: 'ACM Conference on Computer and Communications Security (CCS)',
        co_authors: [],
        domain: 'Blockchain',
        keywords: ['defi', 'flash loans', 'symbolic execution']
      },
      {
        title: 'Interactive Theorem Proving for Autonomous Agent Governance Smart Contracts',
        year: 2023,
        doi: '10.1007/978-3-031-30823-9_8',
        citations: 42,
        venue: 'Tools and Algorithms for the Construction and Analysis of Systems (TACAS)',
        co_authors: ['Dr. Marcus Holloway'],
        domain: 'Software Engineering',
        keywords: ['dao governance', 'theorem proving', 'smart contracts']
      },
      {
        title: 'Vulnerability Benchmarking of Cross-Chain Bridge Protocols',
        year: 2022,
        doi: '10.1109/TDSC.2022.3219012',
        citations: 78,
        venue: 'IEEE Transactions on Dependable and Secure Computing',
        co_authors: ['Dr. Vikramaditya Rao'],
        domain: 'Cybersecurity',
        keywords: ['bridge security', 'cross-chain', 'cryptographic replay']
      },
      {
        title: 'High-Throughput Sharded Consensus with Provable Byzantine Liveness',
        year: 2021,
        doi: '10.1109/TC.2021.3092810',
        citations: 67,
        venue: 'IEEE Transactions on Computers',
        co_authors: [],
        domain: 'Distributed Systems',
        keywords: ['sharding', 'byzantine consensus', 'high throughput']
      }
    ]
  },
  {
    researcher_id: 'FAC-A17-010',
    name: 'Dr. Mateo Rossi',
    department: 'Dipartimento di Elettronica, Informazione e Bioingegneria',
    institution: 'Politecnico di Milano',
    affiliation: 'Human-Robot Interaction & AI Lab',
    scopus_author_id: '56291038491',
    orcid: '0000-0003-4918-2049',
    wos_researcher_id: 'ITA-1920-2020',
    expertise: ['Human-Computer Interaction', 'User Experience in AI', 'Affective Computing', 'Explainable Interfaces'],
    research_areas: ['Human Computer Interaction', 'Artificial Intelligence', 'Robotics'],
    keywords: ['hci', 'human-ai interaction', 'affective computing', 'explainable ai', 'user trust', 'conversational interfaces'],
    h_index: 29,
    i10_index: 48,
    total_citations: 3790,
    current_workload: 1,
    max_workload: 5,
    is_available: true,
    co_authors: ['Dr. Kenji Sato', 'Prof. Lucas Meyer'],
    publications: [
      {
        title: 'Calibrating Human Trust in Autonomous AI Teammates via Interactive Explanations',
        year: 2025,
        doi: '10.1145/3706598.3713910',
        citations: 22,
        venue: 'ACM CHI Conference on Human Factors in Computing Systems',
        co_authors: ['Dr. Kenji Sato'],
        domain: 'Human Computer Interaction',
        keywords: ['human-ai teaming', 'trust calibration', 'interactive explanations']
      },
      {
        title: 'Multimodal Emotion Recognition in Collaborative Remote Classrooms',
        year: 2024,
        doi: '10.1109/TAFFC.2024.3371920',
        citations: 47,
        venue: 'IEEE Transactions on Affective Computing',
        co_authors: [],
        domain: 'Human Computer Interaction',
        keywords: ['affective computing', 'facial microexpressions', 'speech emotion']
      },
      {
        title: 'Designing Gaze-Guided Interfaces for Hands-Free Robot Telemanipulation',
        year: 2023,
        doi: '10.1145/3544548.3580812',
        citations: 64,
        venue: 'ACM CHI',
        co_authors: ['Dr. Kenji Sato'],
        domain: 'Robotics',
        keywords: ['eye tracking', 'gaze interface', 'telemanipulation']
      },
      {
        title: 'Explainable Recommendation Dashboards for Academic Paper Peer Review',
        year: 2022,
        doi: '10.1145/3503252.3531310',
        citations: 83,
        venue: 'ACM Conference on User Modeling, Adaptation and Personalization (UMAP)',
        co_authors: ['Prof. Lucas Meyer'],
        domain: 'Human Computer Interaction',
        keywords: ['peer review', 'recommender interfaces', 'transparency']
      },
      {
        title: 'Evaluating Cognitive Load in Conversational Voice Assistants with EEG Correlates',
        year: 2021,
        doi: '10.1016/j.ijhcs.2021.102690',
        citations: 71,
        venue: 'International Journal of Human-Computer Studies',
        co_authors: [],
        domain: 'Human Computer Interaction',
        keywords: ['cognitive load', 'eeg', 'voice assistant']
      }
    ]
  },
  {
    researcher_id: 'FAC-A17-011',
    name: 'Dr. Fatima Al-Mansoor',
    department: 'Department of Electrical & Computer Engineering',
    institution: 'King Abdullah University of Science and Technology (KAUST)',
    affiliation: 'Cloud & Distributed Computing Lab',
    scopus_author_id: '57192830192',
    orcid: '0000-0002-1920-4819',
    wos_researcher_id: 'SAU-4910-2022',
    expertise: ['Cloud Computing', 'Serverless Architectures', 'Distributed Cache Protocols', 'Microservices'],
    research_areas: ['Cloud Computing', 'Distributed Systems', 'Software Engineering'],
    keywords: ['cloud computing', 'serverless', 'microservices', 'kubernetes', 'distributed caching', 'cold start'],
    h_index: 23,
    i10_index: 37,
    total_citations: 2310,
    current_workload: 2,
    max_workload: 4,
    is_available: true,
    co_authors: ['Prof. Lucas Meyer', 'Dr. Gabriel Silva'],
    publications: [
      {
        title: 'Warm-Start Optimization for Heavy-Model Serverless Function Invocations',
        year: 2025,
        doi: '10.1109/TPDS.2025.3421090',
        citations: 17,
        venue: 'IEEE Transactions on Parallel and Distributed Systems',
        co_authors: ['Dr. Gabriel Silva'],
        domain: 'Cloud Computing',
        keywords: ['serverless', 'cold start mitigation', 'container snapshots']
      },
      {
        title: 'Adaptive Multi-Region Autoscaling for AI Inference Microservices',
        year: 2024,
        doi: '10.1145/3627703.3629570',
        citations: 41,
        venue: 'ACM Symposium on Cloud Computing (SoCC)',
        co_authors: ['Prof. Lucas Meyer'],
        domain: 'Cloud Computing',
        keywords: ['autoscaling', 'cloud inference', 'kubernetes']
      },
      {
        title: 'Consistent In-Memory Key-Value Stores for High-Churn Peer-to-Peer Networks',
        year: 2023,
        doi: '10.1016/j.jpdc.2023.04.009',
        citations: 59,
        venue: 'Journal of Parallel and Distributed Computing',
        co_authors: ['Dr. Gabriel Silva'],
        domain: 'Distributed Systems',
        keywords: ['distributed caching', 'p2p', 'eventual consistency']
      },
      {
        title: 'Carbon-Aware Workload Scheduling in Hyperscale Edge-Cloud Continuums',
        year: 2022,
        doi: '10.1109/TCC.2022.3190123',
        citations: 83,
        venue: 'IEEE Transactions on Cloud Computing',
        co_authors: [],
        domain: 'Cloud Computing',
        keywords: ['green computing', 'carbon awareness', 'hyperscale datacenter']
      },
      {
        title: 'Resilient RPC Communication for Geo-Distributed Autonomous Vehicle Clusters',
        year: 2021,
        doi: '10.1109/ICDCS51616.2021.00049',
        citations: 62,
        venue: 'IEEE International Conference on Distributed Computing Systems (ICDCS)',
        co_authors: ['Dr. Gabriel Silva'],
        domain: 'Distributed Systems',
        keywords: ['rpc', 'geo-distributed', 'autonomous vehicles']
      }
    ]
  },
  {
    researcher_id: 'FAC-A17-012',
    name: 'Dr. Gabriel Silva',
    department: 'Department of Computer Science',
    institution: 'University of São Paulo',
    affiliation: 'Distributed Software Systems Lab',
    scopus_author_id: '56391820491',
    orcid: '0000-0003-9182-3041',
    wos_researcher_id: 'BRA-8291-2021',
    expertise: ['Distributed Systems', 'Fault Tolerance', 'Consensus Algorithms', 'Raft & Paxos Variants'],
    research_areas: ['Distributed Systems', 'Software Engineering', 'Cloud Computing'],
    keywords: ['distributed consensus', 'fault tolerance', 'raft', 'paxos', 'replication', 'state machine replication'],
    h_index: 27,
    i10_index: 44,
    total_citations: 3120,
    current_workload: 1,
    max_workload: 5,
    is_available: true,
    co_authors: ['Dr. Fatima Al-Mansoor', 'Dr. Aris Thorne'],
    publications: [
      {
        title: 'Leaderless Byzantine Fault Tolerant Consensus with Linear Message Complexity',
        year: 2025,
        doi: '10.1145/3694710',
        citations: 20,
        venue: 'ACM Symposium on Principles of Distributed Computing (PODC)',
        co_authors: ['Dr. Aris Thorne'],
        domain: 'Distributed Systems',
        keywords: ['pbft', 'linear complexity', 'leaderless consensus']
      },
      {
        title: 'Optimistic State Replication for High-Frequency Autonomous Trading Agents',
        year: 2024,
        doi: '10.1109/TPDS.2024.3382910',
        citations: 51,
        venue: 'IEEE Transactions on Parallel and Distributed Systems',
        co_authors: ['Dr. Fatima Al-Mansoor'],
        domain: 'Distributed Systems',
        keywords: ['state replication', 'low latency', 'speculative execution']
      },
      {
        title: 'Dynamic Sharding in Geospatially Distributed NoSQL Stores',
        year: 2023,
        doi: '10.14778/3598581.3598592',
        citations: 69,
        venue: 'Proceedings of the VLDB Endowment',
        co_authors: [],
        domain: 'Data Science',
        keywords: ['sharding', 'nosql', 'geospatial partitioning']
      },
      {
        title: 'Automated Chaos Injection for Verification of Microservice Recovery Invariants',
        year: 2022,
        doi: '10.1109/TSE.2022.3179210',
        citations: 88,
        venue: 'IEEE Transactions on Software Engineering',
        co_authors: ['Dr. Fatima Al-Mansoor'],
        domain: 'Software Engineering',
        keywords: ['chaos engineering', 'fault injection', 'microservice resilience']
      },
      {
        title: 'Byzantine Fault Tolerant Clock Synchronization for Sensor Networks',
        year: 2021,
        doi: '10.1016/j.comnet.2021.108192',
        citations: 55,
        venue: 'Computer Networks',
        co_authors: [],
        domain: 'IoT',
        keywords: ['clock synchronization', 'sensor networks', 'byzantine']
      }
    ]
  },
  {
    researcher_id: 'FAC-A17-013',
    name: 'Dr. Claire Dubost',
    department: 'Département Informatique',
    institution: 'Sorbonne Université',
    affiliation: 'Laboratoire d’Informatique de Paris 6 (LIP6)',
    scopus_author_id: '57193849102',
    orcid: '0000-0002-8192-3019',
    wos_researcher_id: 'FRA-9201-2020',
    expertise: ['Software Testing', 'Automated Program Repair', 'Code Intelligence', 'Static Analysis'],
    research_areas: ['Software Engineering', 'Machine Learning', 'Cybersecurity'],
    keywords: ['software testing', 'automated program repair', 'llm code generation', 'fuzzing', 'mutation testing'],
    h_index: 30,
    i10_index: 51,
    total_citations: 3950,
    current_workload: 2,
    max_workload: 4,
    is_available: true,
    co_authors: ['Dr. Marcus Holloway', 'Prof. Elena Rostova'],
    publications: [
      {
        title: 'Neural Program Repair Guided by Dynamic Execution Traces and Type Contracts',
        year: 2025,
        doi: '10.1145/3691620.3695210',
        citations: 25,
        venue: 'ACM International Conference on Architectural Support for Programming Languages (ASPLOS)',
        co_authors: ['Prof. Elena Rostova'],
        domain: 'Software Engineering',
        keywords: ['program repair', 'execution traces', 'type contracts']
      },
      {
        title: 'Differential Fuzzing of Smart Contract Interpreters using Guided Seed Generation',
        year: 2024,
        doi: '10.1109/ICSE48619.2024.00084',
        citations: 58,
        venue: 'IEEE/ACM International Conference on Software Engineering (ICSE)',
        co_authors: ['Dr. Marcus Holloway'],
        domain: 'Software Engineering',
        keywords: ['fuzzing', 'smart contracts', 'differential testing']
      },
      {
        title: 'Evaluating LLM-Generated Unit Tests for Regression Bug Detection',
        year: 2023,
        doi: '10.1145/3597503.3639102',
        citations: 112,
        venue: 'ACM Transactions on Software Engineering and Methodology (TOSEM)',
        co_authors: [],
        domain: 'Software Engineering',
        keywords: ['test generation', 'llm evaluation', 'regression testing']
      },
      {
        title: 'Mutation-Guided Concolic Testing for Safety-Critical Autonomous Systems',
        year: 2022,
        doi: '10.1109/TSE.2022.3168219',
        citations: 79,
        venue: 'IEEE Transactions on Software Engineering',
        co_authors: ['Prof. Elena Rostova'],
        domain: 'Software Engineering',
        keywords: ['concolic testing', 'mutation analysis', 'autonomous safety']
      },
      {
        title: 'Static Taint Tracking for Cross-Language Microservice Dependencies',
        year: 2021,
        doi: '10.1145/3468264.3468590',
        citations: 68,
        venue: 'ACM Joint European Software Engineering Conference and Symposium on the Foundations of Software Engineering (ESEC/FSE)',
        co_authors: [],
        domain: 'Cybersecurity',
        keywords: ['taint analysis', 'static analysis', 'vulnerability detection']
      }
    ]
  },
  {
    researcher_id: 'FAC-A17-014',
    name: 'Dr. Wei Zhang',
    department: 'Department of Computer Science & Technology',
    institution: 'Tsinghua University',
    affiliation: 'State Key Laboratory of Intelligent Technology and Systems',
    scopus_author_id: '56491029381',
    orcid: '0000-0001-9182-4910',
    wos_researcher_id: 'CHN-7182-2019',
    expertise: ['Deep Learning Theory', 'Optimization Dynamics', 'Overparameterization', 'Transformer Scaling Laws'],
    research_areas: ['Deep Learning', 'Machine Learning', 'Artificial Intelligence'],
    keywords: ['deep learning theory', 'loss landscapes', 'generalization bounds', 'scaling laws', 'gradient flow'],
    h_index: 38,
    i10_index: 79,
    total_citations: 7120,
    current_workload: 3,
    max_workload: 5,
    is_available: true,
    co_authors: ['Prof. Sofia Chen', 'Dr. Kenji Sato'],
    publications: [
      {
        title: 'Exact Asymptotics of Generalization in Overparameterized Attention Layers',
        year: 2025,
        doi: '10.1145/3698120',
        citations: 34,
        venue: 'Journal of the ACM',
        co_authors: ['Prof. Sofia Chen'],
        domain: 'Deep Learning',
        keywords: ['generalization bounds', 'overparameterization', 'attention theory']
      },
      {
        title: 'Empirical Scaling Laws for Mixture-of-Experts with Sparsity Constraints',
        year: 2024,
        doi: '10.48550/arXiv.2403.01928',
        citations: 130,
        venue: 'NeurIPS 2024 (Oral)',
        co_authors: [],
        domain: 'Deep Learning',
        keywords: ['mixture of experts', 'scaling laws', 'sparsity']
      },
      {
        title: 'Implicit Regularization in Stochastic Gradient Descent along Manifolds',
        year: 2023,
        doi: '10.1137/22M1498102',
        citations: 92,
        venue: 'SIAM Journal on Mathematics of Data Science',
        co_authors: ['Prof. Sofia Chen'],
        domain: 'Machine Learning',
        keywords: ['implicit bias', 'sgd dynamics', 'manifold optimization']
      },
      {
        title: 'Provable Convergence of Non-Convex Transformer Pre-Training under Sharpness Minimization',
        year: 2022,
        doi: '10.1609/aaai.v36i8.20810',
        citations: 105,
        venue: 'AAAI Conference on Artificial Intelligence',
        co_authors: ['Dr. Kenji Sato'],
        domain: 'Deep Learning',
        keywords: ['sam optimizer', 'convergence analysis', 'sharpness aware']
      },
      {
        title: 'Double Descent in Linear Regression with Structured Random Features',
        year: 2021,
        doi: '10.1093/imaiai/iaab018',
        citations: 118,
        venue: 'Information and Inference: A Journal of the IMA',
        co_authors: [],
        domain: 'Machine Learning',
        keywords: ['double descent', 'random features', 'kernel ridge']
      }
    ]
  },
  {
    researcher_id: 'FAC-A17-015',
    name: 'Dr. Elena Nesterova',
    department: 'School of Computer Science',
    institution: 'University of Waterloo',
    affiliation: 'Waterloo Data Systems Group',
    scopus_author_id: '57194810283',
    orcid: '0000-0002-3849-1029',
    wos_researcher_id: 'CAN-8291-2022',
    expertise: ['Data Science', 'Feature Engineering', 'Big Data Streaming', 'Time Series Forecasting'],
    research_areas: ['Data Science', 'Machine Learning', 'Cloud Computing'],
    keywords: ['data science', 'time series', 'feature selection', 'streaming data', 'anomaly detection', 'tabular deep learning'],
    h_index: 25,
    i10_index: 43,
    total_citations: 2890,
    current_workload: 1,
    max_workload: 4,
    is_available: true,
    co_authors: ['Dr. Priya Venkatesh', 'Dr. Fatima Al-Mansoor'],
    publications: [
      {
        title: 'Transformer-Based Multi-Horizon Probabilistic Time Series Forecasting with Exogenous Signals',
        year: 2025,
        doi: '10.1145/3690182',
        citations: 29,
        venue: 'ACM Transactions on Knowledge Discovery from Data (TKDD)',
        co_authors: ['Dr. Priya Venkatesh'],
        domain: 'Data Science',
        keywords: ['time series', 'probabilistic forecasting', 'attention']
      },
      {
        title: 'Online Feature Drift Detection in High-Throughput Sensor Streams',
        year: 2024,
        doi: '10.1109/TKDE.2024.3378912',
        citations: 56,
        venue: 'IEEE Transactions on Knowledge and Data Engineering',
        co_authors: ['Dr. Fatima Al-Mansoor'],
        domain: 'Data Science',
        keywords: ['concept drift', 'streaming data', 'change point detection']
      },
      {
        title: 'Benchmark Analysis of Tabular Deep Learning vs Gradient Boosted Decision Trees',
        year: 2023,
        doi: '10.1016/j.patcog.2023.109812',
        citations: 142,
        venue: 'Pattern Recognition',
        co_authors: [],
        domain: 'Machine Learning',
        keywords: ['tabular data', 'xgboost', 'lightgbm', 'tabnet']
      },
      {
        title: 'Distributed Sketching for Approximate Quantiles in Cloud Data Lakes',
        year: 2022,
        doi: '10.1145/3514221.3526154',
        citations: 64,
        venue: 'ACM SIGMOD International Conference on Management of Data',
        co_authors: ['Dr. Fatima Al-Mansoor'],
        domain: 'Cloud Computing',
        keywords: ['data sketching', 'quantiles', 'data lakes']
      },
      {
        title: 'Scalable Graph Embeddings for Fraud Detection in E-Commerce Transactions',
        year: 2021,
        doi: '10.1145/3447548.3467310',
        citations: 85,
        venue: 'ACM SIGKDD Conference on Knowledge Discovery and Data Mining',
        co_authors: ['Dr. Priya Venkatesh'],
        domain: 'Data Science',
        keywords: ['fraud detection', 'graph neural networks', 'embeddings']
      }
    ]
  },
  {
    researcher_id: 'FAC-A17-016',
    name: 'Dr. Radhika Sharma',
    department: 'Department of Computer Science and Engineering',
    institution: 'Vignan Foundation for Science, Technology & Research',
    affiliation: 'School of Computing, Vignan University',
    scopus_author_id: '57193821000',
    orcid: '0000-0002-1825-0097',
    wos_researcher_id: 'IND-7182-2018',
    expertise: ['Autonomous Multi-Agent Systems', 'Intelligent Traffic Networks', 'Medical Vision AI', 'Smart Grid Dispatch'],
    research_areas: ['Artificial Intelligence', 'Multi-Agent Systems', 'Computer Vision'],
    keywords: ['autonomous agents', 'traffic management', 'medical vision', 'smart grid', 'vignan'],
    h_index: 33,
    i10_index: 64,
    total_citations: 4980,
    current_workload: 4,
    max_workload: 5,
    is_available: true,
    co_authors: ['Dr. Aris Thorne', 'Dr. Ananya Joshi'],
    publications: [
      {
        title: 'Decentralized Multi-Agent Traffic Signal Control with Deep Q-Learning',
        year: 2024,
        doi: '10.1109/TITS.2024.3371910',
        citations: 62,
        venue: 'IEEE Transactions on Intelligent Transportation Systems',
        co_authors: ['Dr. Aris Thorne'],
        domain: 'Multi-Agent Systems',
        keywords: ['traffic signal control', 'q-learning', 'multi-agent']
      },
      {
        title: 'Dual-Stage Attention Networks for Automated Diabetic Retinopathy Screening',
        year: 2023,
        doi: '10.1016/j.eswa.2023.120918',
        citations: 77,
        venue: 'Expert Systems with Applications',
        co_authors: ['Dr. Ananya Joshi'],
        domain: 'Computer Vision',
        keywords: ['diabetic retinopathy', 'attention networks', 'medical ai']
      },
      {
        title: 'Distributed Voltage Stabilization in Renewable-Heavy Distribution Feeders',
        year: 2022,
        doi: '10.1109/TPWRS.2022.3189102',
        citations: 89,
        venue: 'IEEE Transactions on Power Systems',
        co_authors: ['Dr. Aris Thorne'],
        domain: 'Distributed Systems',
        keywords: ['voltage stabilization', 'renewables', 'smart grid']
      },
      {
        title: 'Coordinated Charging of Autonomous Electric Vehicle Fleets',
        year: 2021,
        doi: '10.1016/j.apenergy.2021.117210',
        citations: 94,
        venue: 'Applied Energy',
        co_authors: [],
        domain: 'Multi-Agent Systems',
        keywords: ['ev fleet', 'charge scheduling', 'multi-agent coordination']
      },
      {
        title: 'Federated Edge Learning for Medical Image Diagnostics under Strict Privacy',
        year: 2021,
        doi: '10.1109/JBHI.2021.3098120',
        citations: 78,
        venue: 'IEEE Journal of Biomedical and Health Informatics',
        co_authors: ['Dr. Ananya Joshi'],
        domain: 'Healthcare AI',
        keywords: ['federated learning', 'medical imaging', 'differential privacy']
      },
      {
        title: 'Consensus Protocols for Smart City Traffic Light Optimization',
        year: 2020,
        doi: '10.1016/j.trc.2020.102690',
        citations: 110,
        venue: 'Transportation Research Part C',
        co_authors: ['Dr. Aris Thorne'],
        domain: 'Artificial Intelligence',
        keywords: ['traffic control', 'smart city', 'consensus']
      }
    ]
  },
  {
    researcher_id: 'FAC-A17-017',
    name: 'Prof. Elena Rostova',
    department: 'Computer Science and Artificial Intelligence Laboratory (CSAIL)',
    institution: 'Massachusetts Institute of Technology',
    affiliation: 'MIT CSAIL',
    scopus_author_id: '56481029481',
    orcid: '0000-0001-4921-7782',
    wos_researcher_id: 'USA-9182-2017',
    expertise: ['Autonomous Agents', 'Software Synthesis', 'Formal Verification', 'Multi-Agent Auctions'],
    research_areas: ['Artificial Intelligence', 'Software Engineering', 'Multi-Agent Systems'],
    keywords: ['autonomous agents', 'synthesis', 'formal methods', 'auctions', 'game theory', 'mit'],
    h_index: 45,
    i10_index: 92,
    total_citations: 11400,
    current_workload: 3,
    max_workload: 5,
    is_available: true,
    co_authors: ['Dr. Aris Thorne', 'Dr. Claire Dubost'],
    publications: [
      {
        title: 'Synthesizing Provably Safe Strategic Policies for Autonomous Fleet Logistics',
        year: 2025,
        doi: '10.1145/3701928',
        citations: 38,
        venue: 'Communications of the ACM',
        co_authors: ['Dr. Claire Dubost'],
        domain: 'Artificial Intelligence',
        keywords: ['policy synthesis', 'fleet logistics', 'formal safety']
      },
      {
        title: 'Game-Theoretic Foundations for Autonomous Multi-Agent Marketplace Auctions',
        year: 2024,
        doi: '10.1287/opre.2023.0192',
        citations: 94,
        venue: 'Operations Research',
        co_authors: ['Dr. Aris Thorne'],
        domain: 'Multi-Agent Systems',
        keywords: ['game theory', 'marketplace auctions', 'agent incentives']
      },
      {
        title: 'Neural Deductive Synthesis for Concurrent Protocol Implementations',
        year: 2023,
        doi: '10.1145/3591230',
        citations: 82,
        venue: 'ACM Transactions on Programming Languages and Systems (TOPLAS)',
        co_authors: ['Dr. Claire Dubost'],
        domain: 'Software Engineering',
        keywords: ['program synthesis', 'concurrent protocols', 'formal logic']
      },
      {
        title: 'Provably Correct Multi-Agent Coordination through Linear Temporal Logic',
        year: 2022,
        doi: '10.1007/s10472-022-09812-4',
        citations: 88,
        venue: 'Annals of Mathematics and Artificial Intelligence',
        co_authors: [],
        domain: 'Software Engineering',
        keywords: ['ltl', 'formal verification', 'multi-agent coordination']
      },
      {
        title: 'Truthful Multi-Unit Combinatorial Auctions with Bounded Verification Overhead',
        year: 2022,
        doi: '10.1287/ijoc.2022.1190',
        citations: 76,
        venue: 'INFORMS Journal on Computing',
        co_authors: ['Dr. Aris Thorne'],
        domain: 'Multi-Agent Systems',
        keywords: ['combinatorial auctions', 'game theory', 'incentive compatibility']
      },
      {
        title: 'Compositional Specification of Autonomous Software Agents',
        year: 2021,
        doi: '10.1145/3468264.3468581',
        citations: 91,
        venue: 'ACM Joint European Software Engineering Conference (ESEC/FSE)',
        co_authors: ['Dr. Claire Dubost'],
        domain: 'Software Engineering',
        keywords: ['compositional verification', 'software agents', 'contracts']
      },
      {
        title: 'Decentralized Market Mechanisms for Resilient Microgrid Power Bidding',
        year: 2020,
        doi: '10.1109/TSG.2020.2981023',
        citations: 130,
        venue: 'IEEE Transactions on Smart Grid',
        co_authors: ['Dr. Aris Thorne'],
        domain: 'Distributed Systems',
        keywords: ['microgrid', 'auction theory', 'smart grid']
      }
    ]
  },
  {
    researcher_id: 'FAC-A17-018',
    name: 'Dr. Tariq Al-Hassan',
    department: 'Department of Electrical & Computer Engineering',
    institution: 'University of Illinois Urbana-Champaign',
    affiliation: 'Coordinated Science Laboratory, UIUC',
    scopus_author_id: '57281903912',
    orcid: '0000-0003-9182-1029',
    wos_researcher_id: 'USA-2918-2021',
    expertise: ['Autonomous Driving', 'Sensor Fusion', 'LiDAR Object Detection', '3D Vision'],
    research_areas: ['Computer Vision', 'Robotics', 'Artificial Intelligence'],
    keywords: ['autonomous driving', 'sensor fusion', 'lidar', 'point clouds', '3d detection', 'kalman filter'],
    h_index: 28,
    i10_index: 47,
    total_citations: 3510,
    current_workload: 2,
    max_workload: 4,
    is_available: true,
    co_authors: ['Dr. Kenji Sato', 'Dr. Wei Zhang'],
    publications: [
      {
        title: 'Robust Multi-Modal Camera-LiDAR Fusion under Extreme Weather Degradation',
        year: 2025,
        doi: '10.1109/CVPR52688.2025.01829',
        citations: 33,
        venue: 'IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR)',
        co_authors: ['Dr. Kenji Sato'],
        domain: 'Computer Vision',
        keywords: ['camera-lidar fusion', 'adverse weather', 'autonomous driving']
      },
      {
        title: 'Sparse 3D Voxel Transformers for Fast Bird’s-Eye-View Object Detection',
        year: 2024,
        doi: '10.1109/TPAMI.2024.3391820',
        citations: 74,
        venue: 'IEEE Transactions on Pattern Analysis and Machine Intelligence (TPAMI)',
        co_authors: ['Dr. Wei Zhang'],
        domain: 'Computer Vision',
        keywords: ['voxel transformer', 'bev detection', 'point cloud']
      },
      {
        title: 'End-to-End Trajectory Prediction for Urban Driving with Occupancy Flow Grids',
        year: 2023,
        doi: '10.1109/TIV.2023.3289120',
        citations: 67,
        venue: 'IEEE Transactions on Intelligent Vehicles',
        co_authors: [],
        domain: 'Robotics',
        keywords: ['trajectory prediction', 'occupancy flow', 'motion planning']
      },
      {
        title: 'Multi-Object Tracking in Dense Urban Traffic with Graph Neural Networks',
        year: 2022,
        doi: '10.1109/ITSC48978.2022.9922109',
        citations: 85,
        venue: 'IEEE International Conference on Intelligent Transportation Systems (ITSC)',
        co_authors: ['Dr. Kenji Sato'],
        domain: 'Computer Vision',
        keywords: ['multi-object tracking', 'gnn', 'kalman filter']
      },
      {
        title: 'Uncertainty-Aware Radar-Camera Fusion for Autonomous Emergency Braking',
        year: 2021,
        doi: '10.1109/TITS.2021.3082910',
        citations: 92,
        venue: 'IEEE Transactions on Intelligent Transportation Systems',
        co_authors: [],
        domain: 'Robotics',
        keywords: ['radar fusion', 'emergency braking', 'kalman filter']
      },
      {
        title: 'Self-Supervised Monocular Depth Estimation on Panoramic Automotive Sensors',
        year: 2020,
        doi: '10.1109/ICRA40947.2020.9197120',
        citations: 79,
        venue: 'IEEE International Conference on Robotics and Automation (ICRA)',
        co_authors: ['Dr. Wei Zhang'],
        domain: 'Computer Vision',
        keywords: ['monocular depth', 'self-supervised', 'panoramic']
      }
    ]
  }
];
